### ISSUE TITLE
The TARDiS interior is messed up

### ISSUE THREAD

**Issue by REDSTAR153** [MattJeanes/TARDIS#481] opened 2021-11-03 15:18 UTC
I have no idea what happened but
![image](https://user-images.githubusercontent.com/79068684/140088790-5e057ae9-ff4e-4f9f-885d-ade3a4a15a47.png)
![image](https://user-images.githubusercontent.com/79068684/140089046-4ddbbe50-af12-484a-964b-0c88776c2ca3.png)

**Comment by MattJeanes** [comment] 2021-11-03 15:30
Set your model detail in-game to high

Duplicate of https://github.com/MattJeanes/TARDIS/issues/474, closing

**Closed by MattJeanes** 2021-11-03 15:30 UTC

**Comment by REDSTAR153** [comment] 2021-11-03 23:29
fixed it

**Comment by REDSTAR153** [comment] 2021-11-03 23:30
thanks
