### ISSUE TITLE
Players visible while in TARDIS

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#202] opened 2016-09-22 17:56 UTC
I have noticed that players tend to be influenced by the players Seen in the invisible interior.

What about an rendermode like distortion if players are inside? ( exept doors are open to ensure visibility if someone is looking inside )

**Comment by Noname12345GER** [comment] 2016-11-12 14:19
I know it has to do something about the Cordon, but what about Diamond it if the doors are closed?

**Comment by MattJeanes** [comment] 2016-11-12 15:29
It may work, I'll have to give it a go

**Comment by Noname12345GER** [comment] 2016-11-12 17:10
Players also Shooting the interior for the lolz. Is there a way to stop damage if outsiders shoot it? Maybe check if attacker is actually in the TARDIS?

**Comment by MattJeanes** [comment] 2020-05-10 22:50
Closing as dupe of #83

**Closed by MattJeanes** 2020-05-10 22:50 UTC
