### ISSUE TITLE
Materialization Edit

### ISSUE THREAD

**Issue by Septonix** [MattJeanes/TARDIS#239] opened 2017-04-21 22:08 UTC
Ok, i realise upon using this that it would be cool if that the TARDIS materializes on you then what if you got teleported into the interior? Just a cool feature i thought would be fun to use in RP situations. (I KNOW This happens in the Legacy but i mean the re-write)

*Told to Split*

**Comment by MattJeanes** [comment] 2017-04-22 00:48
Duplicate of #148

**Closed by MattJeanes** 2017-04-22 00:48 UTC
