### ISSUE TITLE
music box

### ISSUE THREAD

**Issue by molda76** [MattJeanes/TARDIS#434] opened 2021-03-22 07:50 UTC
could you add a popup for music like there used to be in legacy, except sourcing the music from thr tardis folder rather than a website? similiar to thr mat/demat issue i posted.
I know you can link a sound to like a button but it disables when you enter 3rd mode flight and having too many buttons for just songs would suck

**Comment by parar020100** [comment] 2021-11-09 08:16
This seems like a duplicate of #411 
Closing for now, if it is different, please, clarify

**Closed by parar020100** 2021-11-09 08:16 UTC
Labels: v_duplicate, r_DECLINED
