### ISSUE TITLE
Adding a shield 

### ISSUE THREAD

**Issue by ATMmaguire** [MattJeanes/TARDIS#616] opened 2022-02-05 21:08 UTC
I think it would be very cool to add a shield which has a certain amount of power. And it can stop phys gun from moving the tardis. Also it can be set to only allow the owner in the tardis
i think this would be a very cool idea and i would love if his could be added

**Comment by AmyJeanes** [comment] 2022-02-06 00:30
Duplicate of #371

**Closed as completed by AmyJeanes** 2022-02-06 00:30 UTC
