### ISSUE TITLE
Shielding

### ISSUE THREAD

**Issue by Woogull** [MattJeanes/TARDIS#212] opened 2016-10-26 00:52 UTC
What could be cool is having shielding that players can enter but non-friendly NPCs cannot. It would also be cool if you could whitelist and blacklist players. 
I think it would need a charge though, so it charges over time and there's limited use.

**Comment by kennyrkun** [comment] 2016-10-26 04:31
whitelist/blacklist is planned (#164)

NPCs by default will have a *very* hard time making their way into the TARDIS, so this would be almost useless, not to mention that shielding in general has been denied many times by Matt.

**Comment by Noname12345GER** [comment] 2016-10-26 05:32
An disabled ConVar would be nice for this like TARDIS_shields = "0"
TARDIS_Shield_adminonly = "0"

This way Owners Can select.

**Comment by Woogull** [comment] 2016-10-28 12:56
kennyrkun, I meant something more like in "parting of the ways" where the shielding is extended outside the tardis so that the daleks can't kill them, meaning that the NPCs will be stopped outside the tardis, I am aware that mobs can't follow people inside the tardis.

**Comment by Noname12345GER** [comment] 2016-10-28 22:02
Don't forget the deflected dalek missle before they are landed and talked to the daleks. CAP has some nice Rocket deflection. Similar to the gunships Anti Rocket tactic.

**Comment by Noname12345GER** [comment] 2016-11-02 21:06
If ewerything else fails, i would be for shields with would have to recharge after in use for 1 minute

**Comment by MattJeanes** [comment] 2016-11-06 20:06
I've said many times that there will be no shields, the tardis is not related to weaponry. There will however be blacklists/whitelists as @kennyrkun mentioned, so that should be what you're looking for.

Closing as duplicate of #60

**Closed by MattJeanes** 2016-11-06 20:06 UTC
