### ISSUE TITLE
Many controls still work even with power off

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#513] opened 2021-11-16 10:31 UTC
"Even with no power, the majority of buttons inside still work, HADS, door switch, wibbly lever, anti-grav, atom accelerator, etc."

Reported by Cheaple on Discord

**Comment by parar020100** [comment] 2021-11-16 10:33
Duplicate of #454

**Closed** 2021-11-16 10:32 UTC
Labels: v_duplicate, r_DECLINED
