### ISSUE TITLE
My Idea for Hads

### ISSUE THREAD

**Issue by DJNEFFYFRESH** [MattJeanes/TARDIS#531] opened 2021-11-26 21:50 UTC
Suggestion: If the sonic is not linked to the Tardis and HADS gets triggered the Tardis will land somewhere random. 

Alternative Suggestion: If the Tardis gets triggered by HADS  and there is no sonic linked it will eventually land on you possibly giving you a chat warning. But if your sonic is linked It will still land at a random place or on a waypoint but your sonic might get a signal that you can track.

**Comment by parar020100** [comment] 2021-11-29 06:17
Technically, a duplicate of #369
I'm closing this one, and copying the suggestion text to that discussion

**Closed by parar020100** 2021-11-29 06:17 UTC
Labels: v_duplicate, r_DECLINED
