### ISSUE TITLE
Door windows don't change with skins

### ISSUE THREAD

**Issue by theangelcastiel** [MattJeanes/TARDIS#262] opened 2017-05-14 19:46 UTC
I'm not sure if it's an actual bug or if there were no proper windows actually made for the other skins, but this always bothers me. It's not mentioned in bugs though.
![image](https://cloud.githubusercontent.com/assets/14117498/26037191/b8f18ae4-38ab-11e7-9841-38c4f25539e3.png)

**Comment by theangelcastiel** [comment] 2017-05-14 19:48
Sorry, I didn't think to check closed bugs.
#123

**Comment by theangelcastiel** [comment] 2017-05-14 19:48
But it still doesn't work, lol.

**Comment by MattJeanes** [comment] 2017-05-14 23:30
Dupe of #123

**Closed by MattJeanes** 2017-05-14 23:30 UTC
