### ISSUE TITLE
Black Tardis

### ISSUE THREAD

**Issue by xDarkAcidx** [MattJeanes/TARDIS#275] opened 2017-05-25 00:49 UTC
For a while now, I've been having a big problem with spawning the TARDIS. When I spawned it in, everything looked normal until I saw the doors. The doors are black. Thinking nothing of it, I opened it, and it registered that I opened it, but the doors remained black. Also, the TARDIS is just a regular police box now. I cannot go more than a foot through it and can see out the other end. When I open up console, this continuously pops up:

[ERROR] lua/entities/gmod_door_interior/modules/sh_portals.lua:140: attempt to index global 'wp' (a nil value)
  1. v - lua/entities/gmod_door_interior/modules/sh_portals.lua:140
   2. CallHook - lua/entities/gmod_door_interior/shared.lua:31
    3. CallHook - lua/entities/gmod_tardis_interior/shared.lua:28
     4. DrawOverride - lua/tardis/sh_parts.lua:12
      5. v - lua/entities/gmod_tardis_interior/modules/cl_parts.lua:7
       6. CallHook - lua/entities/gmod_tardis_interior/shared.lua:34
        7. v - lua/doors/sh_hooks.lua:32
         8. old_hook_call - lua/includes/modules/hook.lua:84
          9. unknown - lua/includes/modules/momo/compat.lua:23

File exists in two addons - possible conflicts! lua/entities/gmod_tardis_interior/shared.lua (TARDIS Rewrite and Doors)

If there is a fix it would be greatly appreciated!

**Comment by MattJeanes** [comment] 2017-05-25 09:15
Hello, I've seen this one a fair bit. I believe it means that your GMod is failing to load the Doors addon, as the error message is basically saying world-portals isn't installed but it's bundled with Doors so GMod must be failing to load it.

I've found that this can often be caused by having loads of addons, have you tried disabling all addons except Rewrite/Doors and see if that works? Just as a test.

**Comment by MattJeanes** [comment] 2017-05-25 09:15
Also, do you get any error messages further up the console?

**Comment by xDarkAcidx** [comment] 2017-05-25 19:21
Thank you for responding so quickly. I do have around 350 addons so that could be contributing to the problem... I just tried disabling all except Rewrite and Doors, and it worked. So I will try to cut down on my addons! I did not get any other messages in console, only the ones mentioned above. 

Thanks again!

**Comment by MattJeanes** [comment] 2017-05-25 19:30
Okay, yeah it sucks gmod just breaks down after so many addons unfortunately. There's nothing I can do so I will close this issue off

**Closed by MattJeanes** 2017-05-25 19:30 UTC
