### ISSUE TITLE
Interior portals don't work in vortex

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#413] opened 2021-03-17 18:07 UTC
if you demat in 2010, portals break

**Comment by MattJeanes** [comment] 2021-03-17 21:49
Unable to reproduce, can you elaborate?
![image](https://user-images.githubusercontent.com/2363642/111543159-96ba3180-876a-11eb-9612-9181099f7901.png)

**Comment by MattJeanes** [comment] 2021-03-18 00:24
Fixed in https://github.com/MattJeanes/Doors/commit/ab16ed37f62a423e109c19a8f1a0112aa44c5660

**Closed by MattJeanes** 2021-03-18 00:24 UTC
Labels: bug
