### ISSUE TITLE
Dynamic-lit Lantern(maybe windows?)

### ISSUE THREAD

**Issue by GsTheMann** [MattJeanes/TARDIS#307] opened 2018-04-13 01:39 UTC
Make the TARDIS rewrite have an option to make all neon-lit things(windows, pull-to-open etc.) dynamic.

**Comment by Win7yes** [comment] 2020-05-10 17:13
Individual extension devs will have to apply this to their exteriors I'm afraid.
There are hooks and data values to check on the power state and switch model skins accordingly.

**Comment by MattJeanes** [comment] 2020-05-10 17:22
@Win7yes The lantern could be done for them all but the exterior windows will need work by each extension author

**Comment by MattJeanes** [comment] 2020-05-10 23:17
Duplicate of #72

**Closed by MattJeanes** 2020-05-10 23:17 UTC
