### ISSUE TITLE
TARDIS Fueling?

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#179] opened 2016-09-06 04:23 UTC
What about spots on the map with you can locate with a Sonic where you can refuel? With a 0.01 Chance of having an Fueling annormality.

Annormality would consist of one of these:
TARDIS exterior/interior desync (disabled door)
Explosions (visually, with interior Shake like crazy)
Creepy Sounds

**Comment by Noname12345GER** [comment] 2016-09-06 04:24
Let's say if you play with a TARDIS for 2 hours it has to refuel.

**Comment by Noname12345GER** [comment] 2016-09-06 04:25
Also, additional Materials are needed for the TARDIS to work like Mercury just like the original one.

**Comment by kennyrkun** [comment] 2016-09-06 21:37
if this were to be added, it should **definitely** be toggleable. if I was just wanted to fuck around for a while I wouldn't want to have to stop and refuel. that would totally ruin my day

**Comment by FailingGravity** [comment] 2016-09-06 21:51
This, imo, should be a mainly RP-only feature. If you're in sandbox, this would become a pain in the ass. I would like more of a FO:WV system of refueling, where you come across the anomaly in flight, and you have chance of "surfing" the wave and refueling the TARDIS. If you can't refuel of that, there's the combination of controls you can press to put the TARDIS into refuel mode.

If this were to be implemented, I would suggest:

- Use fuel in flightmode at a very small rate
- Use fuel while teleporting, at a configurable server rate. If in sandbox, then a user configurable rate.

**Comment by MattJeanes** [comment] 2016-09-06 23:12
Please search before creating issues, this already exists - if you wish to continue discussion continue it on the existing issue.

Closing as duplicate of #42

**Closed by MattJeanes** 2016-09-06 23:12 UTC
Labels: v_duplicate, r_DECLINED

**Comment by Noname12345GER** [comment] 2016-09-07 21:32
Just wanted to rise the issue again as it would be practical to discuss it now.
