### ISSUE TITLE
Tardis skin reverts to default after landing

### ISSUE THREAD

**Issue by BDubbzzz** [MattJeanes/TARDIS#465] opened 2021-03-26 19:36 UTC
I don't know if this has been mentioned anywhere else or if this is just a glitch/bug on my end.

Every time I demat and remat any version of the Tardis, the exterior reverts to its original default exterior settings.
Example: If I put the 2010 box on skin 1 to make the windows light up and I take-off and land, it changes back to skin 0 with the non-lit/black windows.

If it is meant to do this, I apologize for any inconvenience.

**Comment by TheDimensioneer** [comment] 2021-03-26 20:04
I do think that this was intended as it is

**Comment by francodml** [comment] 2021-03-26 20:12
> I do think that this was intended as it is

How so?

This is a sort or known issue. While we don't explicitly change the exterior skin, we do change bodygroups.

If you could, please try to reproduce this issue with no extensions installed, only the TARDIS and its dependencies (Doors for workshop, plus world-portals for GitHub)

**Comment by BDubbbzz** [comment] 2021-03-26 22:06
I disabled all extensions except for TARDIS addon and its dependencies and I still got the skin still would revert back.

**Comment by francodml** [comment] 2021-03-27 00:57
I've tried this and can't reproduce the issue. It won't do this for me at all.

**Comment by francodml** [comment] 2021-03-27 00:58
Does it happen with any interior or just specific ones?

**Comment by BDubbbzz** [comment] 2021-03-27 01:44
Interesting, it was every interior for me. I'm going to restart my PC and see if that fixes the issue.  I will also check GM's cache or other items. Worst case scenario, I'll perform a reinstall of GM and the mods overnight and see if that fixes the issue.

**Comment by BDubbbzz** [comment] 2021-03-27 20:11
After reinstalling GM and doing a much-needed "spring clean" of my mod subscriptions, the issue seems to have been fixed. I still cannot figure out if it was another mod interfering or if it was just a glitch.

**Comment by MattJeanes** [comment] 2021-03-27 20:20
Fascinating, good to know - I would imagine it is a another mod interfering. I'll go ahead and close this issue then, thanks for letting us know.

**Closed by MattJeanes** 2021-03-27 20:20 UTC
Labels: type: (0) - bug
