### ISSUE TITLE
Tardis Hand Controls BUG

### ISSUE THREAD

**Issue by Alldaygaming** [MattJeanes/TARDIS#229] opened 2017-02-13 01:25 UTC
Hey umm when i press E on the console(any console) it does this:
![capture2](https://cloud.githubusercontent.com/assets/15713319/22868197/41a9160c-f1b9-11e6-991a-8c25a575c0d4.PNG)
![capture1](https://cloud.githubusercontent.com/assets/15713319/22868202/4be24936-f1b9-11e6-9609-ae584a1c1713.PNG)

The images are from gm flatgrass but this happens on all the maps. I do not have cracked version of GMod... (I bought the game on Steam)

**Comment by benrob0329** [comment] 2017-02-13 16:01
Its a known bug, try restarting Gmod for the time being if respawning the Tardis doesn't fix it.

**Comment by MattJeanes** [comment] 2017-02-13 19:54
Duplicate of #110

**Closed by MattJeanes** 2017-02-13 19:54 UTC
