### ISSUE TITLE
Tardis door | F4 | Locking and Door Error !

### ISSUE THREAD

**Issue by reede2** [MattJeanes/TARDIS#303] opened 2018-01-16 10:39 UTC
So when you buy a tardis from f4 you get this
https://image.ibb.co/j2hZgm/rp_doctorwhouniverse0014.jpg
```lua
============Tardis f4 Code ==========================
DarkRP.createEntity("TARDIS", {
	ent = "gmod_tardis",
	model = "models/drmatt/tardis/exterior.mdl",
	price = 100,
	max = 1,
	cmd = "TARDIS",
	category = "Other",
	customCheck = function(ply) return CLIENT or
        table.HasValue({TEAM_DOCTOR, TEAM_MASTER, TEAM_TIMELORD}, ply:Team())
    end,
    CustomCheckFailMsg = "Not a timelord",
    spawn = function(ply, tr, tblEnt)
		local ent = ents.Create("gmod_tardis")
		ent:SetCreator(ply)
		ent:Initialize()
		ent:SetPos(tr.HitPos)
		ent:Spawn()
		return ent
	end,
})
==================================================
```
Also when you try to lock it it doesn't let you from the outside but lets you lock it from the inside and it lets you link from inside but not outside is there way to spawn it as if you where spawning it from q when buying f4 because its fine when you spawn it from q

**Comment by reede2** [comment] 2018-01-16 10:55
Update:
i think i fixed the glitchy door thing with it being white when opening tardis  by using this code
but still the lock thing from the outside doesnt work !
DarkRP.createEntity("TARDIS", {
	ent = "gmod_tardis",
	model = "models/drmatt/tardis/exterior.mdl",
	price = 100,
	max = 1,
	cmd = "TARDIs",
	category = "TimeLords",
	customCheck = function(ply) return CLIENT or
	table.HasValue({TEAM_DOCTOR, TEAM_MASTER, TEAM_TIMELORD}, ply:Team())
	end,
	CustomCheckFailMsg = "You can not buy this",
	spawn = function(ply, tr, tblEnt)
		tr.Hit = true
		return scripted_ents.Get(tblEnt.ent):SpawnFunction(ply, tr, tblEnt.ent)
	end,
})

**Comment by reede2** [comment] 2018-01-16 10:57
i proved my self wrong still white but only when i have keys in my hand if i have a phsgun its fine

**Comment by MattJeanes** [comment] 2018-01-16 11:49
Sorry, bit confused here - what issues are you having? Is this related to #13?

**Comment by reede2** [comment] 2018-01-16 12:07
no this is about not able to lock the door from the outside you can lock it from the inside

**Comment by MattJeanes** [comment] 2018-01-16 12:09
Sorry I meant this one: https://github.com/MattJeanes/Sonic-Screwdriver/issues/13

Basically is the sonic not working correctly in DarkRP when trying to link to the TARDIS or make it lock or whatever?

**Comment by reede2** [comment] 2018-01-16 12:10
the sonic works but not on the tardis door like you can use the sonic to open the door but you cant lock or link it from the outside

**Comment by reede2** [comment] 2018-01-16 12:19
my players complain beacuse they cant lock there tardis

**Comment by MattJeanes** [comment] 2018-01-16 12:20
Okay yeah, it's the same issue as https://github.com/MattJeanes/Sonic-Screwdriver/issues/13 - so I will close this as a duplicate of that, follow that issue for updates

**Closed by MattJeanes** 2018-01-16 12:20 UTC
