### ISSUE TITLE
Flight without brakes

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#205] opened 2016-10-03 20:16 UTC
What about an "calm"  flight sound with can be enabled by releasing the brake? 

As Seen in Episode S5E4 The Time of Angles

**Comment by Noname12345GER** [comment] 2016-10-04 11:43
as seen here:
(SPOILERS)
http://dai.ly/x2cup3u?start=346

**Comment by Noname12345GER** [comment] 2016-10-14 02:22
I have noticed science the 2010 seems to be the only TARDIS  apable of doing so, i thought of just adding Support to change flysounds for Extension developers

**Comment by theangelcastiel** [comment] 2016-10-14 04:13
In my opinion, he should do flight w/o brakes for all tardises, it would make life alot easier, and players wouldn't come running to destroy your tardis. But he could also make it like the sound dampeners, which uses up alot of power, so the only things you could do would be fly and teleport...

**Comment by Noname12345GER** [comment] 2016-11-15 22:16
In the series, you always hear the exterior brakes no matter if they are released or not. But for the sake of everybodys Comfort, i would just apply Stealth flight Sound ewerywhere.

**Comment by MattJeanes** [comment] 2020-05-10 23:25
Duplicate of #52

**Closed by MattJeanes** 2020-05-10 23:25 UTC
Labels: enhancement, unsure
