### ISSUE TITLE
DeLorean Teleporter Sound Bug

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#256] opened 2017-05-12 19:23 UTC
If you selected a Position and press Demat, you will go to the inside and usually heqr Demat Sounds. Not the case here.

**Comment by theangelcastiel** [comment] 2017-05-12 20:24
It is known
#245

**Comment by MattJeanes** [comment] 2017-05-12 21:48
Yep, dupe of #245

**Closed by MattJeanes** 2017-05-12 21:48 UTC
