### ISSUE TITLE
Add support for interior preference theme

### ISSUE THREAD

**Issue by AmyJeanes** [MattJeanes/TARDIS#705] opened 2022-08-31 15:29 UTC
Themes should have a default setting which just means interior preference, the preference will still be the default screen as it is today but it means that if a user hasn't explicitly changed the theme it will default to whatever that interior wants.

Basically exactly like how tips work

**Comment by parar020100** [comment] 2022-12-01 13:03
Duplicate of #437

**Closed as completed by parar020100** 2022-12-01 13:03 UTC
Labels: :hash: creator request, :white_check_mark: done_released
