### ISSUE TITLE
Cloaking the TARDIS rewrite just like the non-rewrite TARDIS?

### ISSUE THREAD

**Issue by AdingoD** [MattJeanes/TARDIS#223] opened 2016-11-21 05:00 UTC
Hello.

I think it's time to add the cloaking functionality to the TARDIS rewrite.
If you hold CTRL while in the flight mode, you can see that the TARDIS is "partially - transparent", and when the doors are opened it looks very canon-ish.

All needed is to do such a thing and make the TARDIS completely transparent when doing so.

Good luck.

**Comment by MattJeanes** [comment] 2016-11-21 05:03
Closing as duplicate of #49.

**Closed by MattJeanes** 2016-11-21 05:03 UTC
