### ISSUE TITLE
weird bug pls help

### ISSUE THREAD

**Issue by nutellabrot2** [MattJeanes/TARDIS#758] opened 2022-12-19 15:04 UTC
![image](https://user-images.githubusercontent.com/87707671/208455829-49d95e78-43b5-48b5-b755-3893eb88a2a6.png)

**Comment by parar020100** [comment] 2022-12-19 18:57
This is a duplicate of #758
Please don't spam issues - we can see all of them and try to respond as quickly as we can

**Closed as not planned by parar020100** 2022-12-19 18:57 UTC
Labels: :x: declined_duplicate

**Comment by parar020100** [comment] 2022-12-19 19:19
Apologize, the duplicate is #757
