### ISSUE TITLE
Mat/Demat sounds aren't synced with the animation

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#419] opened 2021-03-17 21:16 UTC

**Comment by parar020100** [comment] 2021-03-17 21:17
Parameters suggested by Valentine:

> Teleport={
        SequenceSpeed=0.77,
        SequenceSpeedFast=0.935,
        DematSequence={
            175,
            230,
            100,
            150,
            50,
            100,
            0
        },
        MatSequence={
            100,
            50,
            150,
            100,
            200,
            150,
            255
        }
    }

**Comment by MattJeanes** [comment] 2021-03-17 21:18
Duplicate of #414, is the actual sequence changed though? I have only updated the speed. If so maybe reopen linked issue with details

**Closed by MattJeanes** 2021-03-17 21:18 UTC
Labels: bug, feature parity
