### ISSUE TITLE
Returning to 1st person

### ISSUE THREAD

**Issue by molda76** [MattJeanes/TARDIS#266] opened 2017-05-22 03:50 UTC
Hello, new destination update is amazing! All i dlnt like is when i go to console, enter 3rd person, set destination and confirm it, it pops me back to 1st person, which is alright, but even if i havent submaterial tool or any other tool in weapon menu it always gives me one... No idea why

**Comment by Noname12345GER** [comment] 2017-05-22 04:07
One what?

**Comment by DoctorCZE** [comment] 2017-05-23 06:35
Yea it just appears in my hands

**Comment by MattJeanes** [comment] 2020-05-10 21:57
Closing as duplicate of #247

**Closed by MattJeanes** 2020-05-10 21:57 UTC
