### ISSUE TITLE
Players are sometimes visible.

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#249] opened 2017-05-03 23:59 UTC
(This affects more the legacy with im using on my server for stability reasons but it's worth looking if the rewrite does the same)

If you are cloaked/dematted, and still in pilot, players can see your playermodel. Maybe apply the debug Material on the player if hes in pilot?

Would be 1 additional Line of Code.

**Comment by MattJeanes** [comment] 2017-05-04 08:35
Legacy is just that, legacy. Not being updated except for fixing it when GMod update breaks it. As for the rewrite I tried to hide the player from people outside the rewrite but it ended up messing rendering right up and the player had no animations, it got pretty weird. Closing as dupe of #83

**Closed by MattJeanes** 2017-05-04 08:35 UTC
