### ISSUE TITLE
glitchy tardis doors help

### ISSUE THREAD

**Issue by JRServers** [MattJeanes/TARDIS#293] opened 2017-07-16 18:41 UTC
some times when my users open the tardis they cant see inside its just white
https://www.imageupload.co.uk/image/DeYG

**Comment by JRServers** [comment] 2017-07-20 13:54
hello

**Comment by MattJeanes** [comment] 2017-07-20 14:19
It's very likely another addon is conflicting with the tardis, I've not seen this issue before so I can only suggest disabling addons until it works to see the culprit

**Comment by JRServers** [comment] 2017-07-20 14:36
http://steamcommunity.com/sharedfiles/filedetails/?id=926707076 
theres addons are the ones i have

**Comment by MattJeanes** [comment] 2017-07-20 14:42
Ok that's great and all but I don't know which addon could cause issues. If it's only some of your players that get this it could be a clientside addon they have if it does it in single player as well for them. You could try disabling certain addons and trial and error it until it works. 

I don't get this issue and I don't know anyone who does so I cannot just fix it unless I know where the problem is

**Comment by JRServers** [comment] 2017-07-20 14:44
we all get it maby its from the way its spawned in from f4

**Comment by MattJeanes** [comment] 2017-07-20 14:45
Is your server forked from DarkRP? Does it work if spawned through the spawn menu normally?

**Comment by JRServers** [comment] 2017-07-20 14:55
its doctor who rp users can buy it from f4

**Comment by MattJeanes** [comment] 2017-07-20 15:02
If you want help can you please put as much info as you can and at least answer my questions. Thanks.

**Comment by JRServers** [comment] 2017-07-23 13:00
Yes My gamemode used to be darkrp its darkrp edited and this is the code  i use to let users buy it from f4 


DarkRP.createEntity("TARDIS", {
	ent = "gmod_tardis",
	model = "models/drmatt/tardis/exterior.mdl",
	price = 100,
	max = 1,
	cmd = "TARDIS",
	category = "TimeLords",
	customCheck = function(ply) return CLIENT or
	table.HasValue({TEAM_DOCTOR, TEAM_MASTER, TEAM_TIMELORD}, ply:Team())
	end,
	CustomCheckFailMsg = "You can not buy this",
	spawn = function(ply, tr, tblEnt)
		local ent = ents.Create("gmod_tardis")
		ent:SetCreator(ply)
		ent:Initialize()
		ent:SetPos(tr.HitPos)
		ent:SetAngles(tr.HitAngles)
		ent:Spawn()
		return ent
	end,
})

**Comment by MattJeanes** [comment] 2017-07-23 13:06
Ah right you're the same guy from that other issue, I thought it was all working OK though? What changed?

**Comment by JRServers** [comment] 2017-07-23 13:07
the doors are just glitchy and stuff they  are white some times when they open it also when they walk in some times they get stuck in the map and its black

**Comment by JRServers** [comment] 2017-07-23 13:13
ignore the little kids calling my server bad in the chat
https://www.imageupload.co.uk/image/DrG5
https://www.imageupload.co.uk/image/DrGD

**Comment by MattJeanes** [comment] 2017-07-23 13:53
Ok you're still not really answering my questions. Does it work when spawned normally through the spawn menu?

**Comment by JRServers** [comment] 2017-07-23 14:00
oh yer it does it works fine when you spawn it from q

**Comment by MattJeanes** [comment] 2017-07-23 14:14
Alright, on the last issue you raised you said it was all working OK. What changed from then to now?

**Comment by JRServers** [comment] 2017-07-23 14:16
No on the last one i ment i could spawn it fine now

**Comment by JRServers** [comment] 2017-07-23 14:17
from f4

**Comment by MattJeanes** [comment] 2017-07-23 14:19
Ok so this issue is solved?

**Comment by JRServers** [comment] 2017-07-23 14:20
not really as its glitchy when spawned from f4  and my users get stuck

**Comment by MattJeanes** [comment] 2017-07-23 15:24
But you just said you could spawn it fine from the F4? Can you please put some effort into your responses. It's making it difficult to help.

**Comment by JRServers** [comment] 2017-07-24 11:49
NO i said icould spawn it ok from q menu but when from f4 its all glitchy

**Comment by Noname12345GER** [comment] 2017-07-24 11:54
Therefore I would think that the glitchy spawning algorythms don't get called when from f4

**Comment by Noname12345GER** [comment] 2017-07-24 11:54
Another reason could be the map. Some Culling if you are too far away.

**Comment by JRServers** [comment] 2017-07-24 11:58
is there a way to restrict tardis to a darkrp team so they can spawn from q

**Comment by MattJeanes** [comment] 2017-07-24 12:23
Okay, I'm guessing here - but try this code and see if that works for you

```lua
DarkRP.createEntity("TARDIS", {
	model = "models/drmatt/tardis/exterior.mdl",
	price = 100,
	max = 1,
	cmd = "TARDIS",
	category = "TimeLords",
	customCheck = function(ply) return CLIENT or
	table.HasValue({TEAM_DOCTOR, TEAM_MASTER, TEAM_TIMELORD}, ply:Team())
	end,
	CustomCheckFailMsg = "You can not buy this",
	spawn = function(ply, tr, tblEnt)
		local EntityName = "gmod_tardis"
		local sent = scripted_ents.GetStored(EntityName).t
		local SpawnFunction = scripted_ents.GetMember(EntityName, "SpawnFunction")
		if ( !SpawnFunction ) then return end
		ent = SpawnFunction(sent, ply, tr, EntityName)

		if IsValid(ent) then
			ent:SetCreator(ply)
		end
		
		return ent
	end,
})
```

**Comment by JRServers** [comment] 2017-07-24 12:26
[ERROR] A runtime error has occurred in "addons/darkrpmodification-master/lua/darkrp_customthings/entities.lua" on line 19.
The best help I can give you is this:

Corrupt entity: TARDIS!
The ent field must be a string.

Hints:
	- No hints, sorry.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
	1. addons/darkrpmodification-master/lua/darkrp_customthings/entities.lua on line 19
	2. function 'doInclude'
	3. gamemodes/doctorwhorp/gamemode/libraries/modificationloader.lua on line 137
	4. gamemodes/doctorwhorp/gamemode/libraries/modificationloader.lua on line 148
	5. gamemodes/doctorwhorp/gamemode/cl_init.lua on line 53
------- End of Simplerr error -------

**Comment by MattJeanes** [comment] 2017-07-24 12:27
Ok I edited my version again, can you try that?

**Comment by JRServers** [comment] 2017-07-24 12:32
no errors but now the tardis doesnt spawn

**Comment by JRServers** [comment] 2017-07-24 12:37
walit no i found one [ERROR] gamemodes/doctorwhorp/gamemode/modules/base/sh_createitems.lua:358: attempt to index local 'ent' (a nil value)

  1. callback - gamemodes/doctorwhorp/gamemode/modules/base/sh_createitems.lua:358

   2. callback - gamemodes/doctorwhorp/gamemode/modules/chat/sv_chat.lua:17

    3. unknown - gamemodes/doctorwhorp/gamemode/modules/chat/sv_chat.lua:255

     4. unknown - lua/includes/modules/concommand.lua:54

**Comment by JRServers** [comment] 2017-07-24 12:48
?

**Comment by MattJeanes** [comment] 2017-07-24 12:53
Right, ok that didn't work then was just a guess anyway. I'm at work right now but when I get home I'll see if I can come up with some code that works. Switch it back to what you had before until then.

**Comment by JRServers** [comment] 2017-07-24 13:54
you sure it isnt the tardis door as you can lock it from the outside now when its from f4

**Comment by JRServers** [comment] 2017-07-24 19:27
are you off work now

**Comment by MattJeanes** [comment] 2017-07-24 21:59
Ok, just messed around in-game and this seems to work to spawn it, though I'm not doing it through DarkRP

```lua
DarkRP.createEntity("TARDIS", {
	ent = "gmod_tardis",
	model = "models/drmatt/tardis/exterior.mdl",
	price = 100,
	max = 1,
	cmd = "TARDIS",
	category = "TimeLords",
	customCheck = function(ply) return CLIENT or
	table.HasValue({TEAM_DOCTOR, TEAM_MASTER, TEAM_TIMELORD}, ply:Team())
	end,
	CustomCheckFailMsg = "You can not buy this",
	spawn = function(ply, tr, tblEnt)
		return scripted_ents.Get(tblEnt.ent):SpawnFunction(ply, tr, tblEnt.ent)
	end,
})
```

**Comment by iamlegend23** [comment] 2017-07-24 22:04
if (goingToGlitch) {dont()}

**Comment by JRServers** [comment] 2017-07-24 22:06
it doesnt spawn the tardis !

**Comment by MattJeanes** [comment] 2017-07-24 22:06
Ok, do you get any messages in the console at all?

**Comment by JRServers** [comment] 2017-07-24 22:07
[ERROR] gamemodes/doctorwhorp/gamemode/modules/base/sh_createitems.lua:358: attempt to index local 'ent' (a nil value)

  1. callback - gamemodes/doctorwhorp/gamemode/modules/base/sh_createitems.lua:358

   2. callback - gamemodes/doctorwhorp/gamemode/modules/chat/sv_chat.lua:17

    3. unknown - gamemodes/doctorwhorp/gamemode/modules/chat/sv_chat.lua:255

     4. unknown - lua/includes/modules/concommand.lua:54

**Comment by MattJeanes** [comment] 2017-07-24 22:09
Okay, try the edited version

**Comment by JRServers** [comment] 2017-07-24 22:14
still doesnt spawn tardis but no error seen in console

**Comment by MattJeanes** [comment] 2017-07-24 22:30
Right ok, can you again try the edited one and tell me if any kind of output in the console comes out? Like this:

![image](https://user-images.githubusercontent.com/2363642/28547727-1162d47c-70c8-11e7-8dc4-13b5dc3d263e.png)

**Comment by JRServers** [comment] 2017-07-24 22:36
Player [1][[JR] Reede✔]

AllSolid	=	false

Entity	=	[NULL Entity]

Fraction	=	1

FractionLeftSolid	=	0

Hit	=	false

HitBox	=	0

HitGroup	=	0

HitNoDraw	=	false

HitNonWorld	=	false

HitNormal	=	0.000000 0.000000 0.000000

HitPos	=	8924.801758 8872.305664 -4257.677246

HitSky	=	false

HitTexture	=	**empty**

HitWorld	=	false

Normal	=	-0.107997 -0.911629 -0.396572

PhysicsBone	=	0

StartPos	=	8933.981445 8949.793945 -4223.968750

StartSolid	=	false

SurfaceProps	=	0

table: 0x24ab1ed8

nil

 

[ERROR] gamemodes/doctorwhorp/gamemode/modules/base/sh_createitems.lua:358: attempt to index local 'ent' (a nil value)

  1. callback - gamemodes/doctorwhorp/gamemode/modules/base/sh_createitems.lua:358

   2. callback - gamemodes/doctorwhorp/gamemode/modules/chat/sv_chat.lua:17

    3. unknown - gamemodes/doctorwhorp/gamemode/modules/chat/sv_chat.lua:255

     4. unknown - lua/includes/modules/concommand.lua:54

**Comment by JRServers** [comment] 2017-07-25 06:24
?

**Comment by MattJeanes** [comment] 2017-07-25 09:40
Can you send the gamemode doctorwhorp, or at least the parts of it I need to make this issue happen, to me so I can test it for myself? Difficult to see what's going on if I can't. You can find my email address on my GitHub profile.

**Comment by JRServers** [comment] 2017-07-25 10:02
all it is  darkrp and adding it to enitites

**Comment by JRServers** [comment] 2017-07-25 10:04
File exists in two addons - possible conflicts! lua/entities/gmod_door_exterior/modules/sh_players.lua (Doors and TARDIS Rewrite)

 

[ERROR] lua/entities/gmod_tardis/modules/sh_players.lua:38: Tried to use a NULL entity!

  1. __newindex - [C]:-1

   2. ClearTardisData - lua/entities/gmod_tardis/modules/sh_players.lua:38

    3. v - lua/entities/gmod_tardis/modules/sh_players.lua:17

     4. CallHook - lua/entities/gmod_tardis/shared.lua:37

      5. PlayerExit - lua/entities/gmod_door_exterior/modules/sh_players.lua:47

       6. v - lua/entities/gmod_door_exterior/modules/sh_interior.lua:90

        7. CallHook - lua/entities/gmod_door_exterior/shared.lua:32

         8. CallHook - lua/entities/gmod_tardis/shared.lua:31

          9. unknown - lua/entities/gmod_door_exterior/shared.lua:75

**Comment by JRServers** [comment] 2017-07-25 10:09
does this error help in any way

**Comment by MattJeanes** [comment] 2017-07-25 10:34
No not really.. even if it is just 'DarkRP and adding it to entities' can you please send it to me? I can't help further unless I can see the issue for myself ingame.

**Comment by JRServers** [comment] 2017-07-25 10:36
can i send it trought email

**Comment by MattJeanes** [comment] 2017-07-25 10:39
Yes, as I said before you can find my email address on my GitHub profile - just zip it up and send it through there

**Comment by JRServers** [comment] 2017-07-25 10:45
i sent it

**Comment by MattJeanes** [comment] 2017-07-25 10:51
Okay thanks, again I am at work now so I will take a look later

**Comment by JRServers** [comment] 2017-07-25 16:50
when do you finsish work

**Comment by iamlegend23** [comment] 2017-07-25 17:45
Don't you think it's a bit rude to assume that the moment he finishes work he should work on GitHub issues, give the guy a break.

**Comment by JRServers** [comment] 2017-07-25 17:52
hmm can you stay the fuck out of this i only asked when he finished work acually so button the fuck out of it

**Comment by JRServers** [comment] 2017-07-25 18:36
I didn't fuckin tell him when to do it or I didn't expect him to do it after work so please fuck off not in the mood to deal with stupid people like you wasting space on here by fucking commenting!

**Comment by iamlegend23** [comment] 2017-07-25 21:17
If you didn't expect him to do it after work then why bother asking talk about "wasting space".

**Comment by JRServers** [comment] 2017-07-25 21:26
i am talking about you commenting on this theres no fuckin neeed

**Comment by thekillertoaster** [comment] 2017-07-25 22:05
comment

**Comment by MattJeanes** [comment] 2017-07-25 22:19
Alright, worked out what was wrong - try this:

```lua
DarkRP.createEntity("TARDIS", {
	ent = "gmod_tardis",
	model = "models/drmatt/tardis/exterior.mdl",
	price = 100,
	max = 1,
	cmd = "TARDIS",
	category = "TimeLords",
	customCheck = function(ply) return CLIENT or
	table.HasValue({TEAM_DOCTOR, TEAM_MASTER, TEAM_TIMELORD}, ply:Team())
	end,
	CustomCheckFailMsg = "You can not buy this",
	spawn = function(ply, tr, tblEnt)
		tr.Hit = true
		return scripted_ents.Get(tblEnt.ent):SpawnFunction(ply, tr, tblEnt.ent)
	end,
})
```

By the way, just so you know I'm not obligated to help you at all here, I'm only doing it because I want to help you to create your RP server which would benefit the wider community. However, please do not start throwing insults around and acting like I'm at your beck and call as it does nothing and only makes me want to help less.

**Comment by reede2** [comment] 2017-07-25 22:29
it fixed it but you can lock from the outside my jr servers gib account has been suspended

**Comment by MattJeanes** [comment] 2017-07-25 22:33
Ok cool, 'you can lock from the outside' what? Can you elaborate?

**Comment by reede2** [comment] 2017-07-25 22:34
sorry i mean you can't lock from the outside or link the tardis from outside the tardis

**Comment by MattJeanes** [comment] 2017-07-25 22:47
Right, seems to be some kind of issue with DarkRPs built-in prop protection which will need further looking into at some point, I've raised an issue [here](https://github.com/MattJeanes/Sonic-Screwdriver/issues/13) for it - but since this particular issue is solved I'll close this off.

**Closed by MattJeanes** 2017-07-25 22:47 UTC
