### ISSUE TITLE
Hand Break

### ISSUE THREAD

**Issue by MrVauxs** [MattJeanes/TARDIS#300] opened 2017-11-28 20:17 UTC
Simple, remember when Doctor wasn't happy about River Song parking the TARDIS silently? Well yeah i just want that, it would add another stealth element to the TARDIS which I would love to use. Also some just hate the noise.
https://www.youtube.com/watch?v=swm1yVHOBbk

**Comment by MattJeanes** [comment] 2020-05-10 22:42
Duplicate of #205

**Closed by MattJeanes** 2020-05-10 22:42 UTC
Labels: feature
